CREATE TABLE IF NOT EXISTS Card (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cardSubjectId int NOT NULL,
    userId int NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cardSubjectId) REFERENCES CardSubject(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);